# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WebARonARKit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WebARonARKit
  pod 'MaterialComponents/ProgressView'
  pod 'MaterialComponents/Palettes'
end
